### ISSUE TITLE
Move items programatically

### ISSUE THREAD

**Issue by RobertoAlvarezCeballos** [blipinsk/FlippableStackView#22]
Hi,

Not really an issue, just a question. Would it be possible to move the items inside the StackView programatically? Imagine I have a button and once I click it I want to see the next item on the array.

Any ideas?

Thank you!

**Comment by blipinsk** [comment]
Hi, 
you have to remember that it's just a `ViewPager`. So how would you do this in the `ViewPager`? 
You have to utilize [`setCurrentItem(int item, true)`](https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setCurrentItem%28int, boolean%29) method.

A different issue might be that you might not see the item being flipped, due to `ViewPager` smooth scroll animation being to fast. To resolve that you can take one of the approaches from [here](http://stackoverflow.com/questions/10812009/change-viewpager-animation-duration-when-sliding-programmatically).

Cheers,
Bartek

**Comment by RobertoAlvarezCeballos** [comment]
Hi,

Thanks you!!! I tried that and for some reason the method wasn't showing up and I thought it was something different. 

Hope it works :)
